# Generated by Django 5.0.6 on 2024-06-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=500)),
                ('title_exist', models.BooleanField(blank=True)),
                ('title_length', models.IntegerField(blank=True)),
                ('description_exist', models.BooleanField(blank=True)),
                ('h1_exist', models.BooleanField(blank=True)),
                ('h_tags_order', models.BooleanField(blank=True)),
                ('h1_count', models.IntegerField(blank=True)),
                ('img_alt', models.BooleanField(blank=True)),
                ('key_words', models.JSONField(blank=True)),
            ],
        ),
    ]
